### ISSUE TITLE
[v8.2.6]: `Cell.getValue()` returns `unknown`. Did return correct type in beta.

### ISSUE THREAD

**Issue by Obiwarn** [TanStack/table#4142]
### Describe the bug

`getValue()`  seems to have unreliable return value typing in v8.2.6. Sometimes `any`, sometimes `unknown`.

e.g. see screenshot from Basic example:

<img width="266" alt="image" src="https://user-images.githubusercontent.com/9539797/178766672-0beca286-0120-4af8-bada-bfbb221b9fb2.png">

AFAIK it returned the correct type (`TTValue`) before.

### Your minimal, reproducible example

x

### Steps to reproduce

x

### Expected behavior

xxxx

### Screenshots or Videos

xxx

### Platform

xxx

### react-table version

8.2.6

### Additional context

x

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by Obiwarn** [comment]
Maybe we could make an optional wrapping utility function?

Because now I need to `as` cast in nearly every column:

```
      {
          accessorKey: "delayInDays",
          cell: (info) => {
            const projectDelayInDays = info.getValue() as number | undefined;

  // ...
```

**Comment by tannerlinsley** [comment]
The getValue function takes an optional generic for casting. getValue<string>()

Tanner Linsley

**Comment by Obiwarn** [comment]
Oh nice, thanks. 

But still sad that we have to do it manually, since the type info is right there.

**Comment by tannerlinsley** [comment]
I mean, it *is* there, but typescript just flat out can’t infer it like you’re thinking. With the function context, it’s possible. I’ll look into shipping some optional def builder functions.

Tanner Linsley

**Comment by Obiwarn** [comment]
Awesome. Thank you!

**Comment by Obiwarn** [comment]
@tannerlinsley I hope not to waste your time, but just in case you haven't tried this yet: 

What about [Distributive Conditional Types](https://www.typescriptlang.org/docs/handbook/2/conditional-types.html#distributive-conditional-types)? 

[Example](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgCJzHZBvAUM5GAeyIC5kBnMKUAcwG59kAjOKckAVwFtnpGAvrlxgAngAcUAYSIAbHiAA8AFXSYANMmUA1OPIgA+ZAF4tu-cggAPSCAAmFZAGsIoojC1q4TAPw4mBASISBQUROxmepwQjIGBSLKy5AAUoMTkqhhwANo6URAAugCUJkZUNCAMAchCBBwQAG78wghEIFTIrfLc7eQy3Upemi5uHl4G2QUmyNlMeHHBEKHh5ABExESr6tUJScipIMQlxkZpRNsEAhf+CwghYRGrrFBbOxCJKWfHp4fnBAD0-2QigAtCDkGAABbARwwiGQlDQKDhZAAdxQqLg4CYV1wBXoQA)

**Comment by gzili** [comment]
> For this to work like beta, we’d need to reintroduce a wrapping utility function to create a column def.

@tannerlinsley Any reason why the utility functions API was ditched? I understand that having plain objects for column defs probably looks cleaner but I really loved having a table object with types, such as column meta, attached to it and having utility functions that inherit the type information from the table object. I thought that exploiting functions to attach types to the table object was really clever and clean. This requirement of casting and global type augmentation to me looks far more clumsy than the beta approach...

**Comment by tannerlinsley** [comment]
Ditched it only temporarily. I wanted the api to work without the utility and I also wanted to remove the requirement for the outer table construct. I am working right now on bringing the utilities back, but as syntactical sugar instead of requirement.

**Comment by Obiwarn** [comment]
resolved by #4185

**Comment by cwagner22** [comment]
I still don't understand why we need to use the helper utility functions to have getValue typing, while it'd have been nice to have it working the way @Pavinati  said, by using the same type as `accessor` under the hood.

**Comment by knitevision1** [comment]
:cry:

**Comment by mshahzebraza** [comment]
The issue still exists for filterFn method.
```tsx
        filterFn: (row, id, filterValue) => {
            return row.getValue(id) // type unknown 
                .toString()
                .includes(filterValue);
        },
```

I can ofcourse cast it to a type but that's not the point.

**Comment by momguide** [comment]
> The issue still exists for filterFn method.
> 
> ```tsx
>         filterFn: (row, id, filterValue) => {
>             return row.getValue(id) // type unknown 
>                 .toString()
>                 .includes(filterValue);
>         },
> ```
> 
> I can ofcourse cast it to a type but that's not the point.

good answer!
but in my case, i used it as

```tsx
        filterFn: (row, id, filterValue) => {
            return filterValue
                       .includes(row.getValue(id).toString())
        },
```

**Comment by reteps** [comment]
+1 on the `filterFn` types not being narrowed. Here was my workaround:

```ts
    columnHelper.accessor('assigned_grader_name', {
      id: 'assigned_grader_name',
      header: 'Assigned grader',
      cell: (info) => info.getValue() || 'Unassigned',
      filterFn: (row, columnId, filterValues: string[]) => {
        if (filterValues.length === 0) return true;
        const current = row.getValue<InstanceQuestionRow['assigned_grader_name']>(columnId);
        if (!current) return filterValues.includes('Unassigned');
        return filterValues.includes(current);
      },
    }),
```

The root cause here seems to be that `columnId` is a string, but for this accessor, my understanding is it will always be the literal `'assigned_grader_name'`.
